### ISSUE TITLE
Route pattern with the default path URL returning the Not found exception.

### ISSUE THREAD

**Issue by harshalizode** [dymmond/esmerald#346]
Hello Everyone!

I have two apps in my project as:

base_url
```
from esmerald import Include
route_patterns = [
         Include(namespace="myapp.employee.urls"),
         Include(namespace="myapp.accounts.urls")
]
```

employee_url
```
route_patterns = [
    Gateway(handler=userlogin),
    Gateway(handler=forcelogout),
]
```

account_url
```
route_patterns = [
    Gateway(handler=useraccount),
]
```
handler as:
```
@post("/login",
      tags=["Login"],
      description="Login to the application with basic authentication.",
      summary="Login", security=[Basic()],
      status_code=status.HTTP_200_OK)
def userlogin():
     ...

@post("/logout",
      status_code=status.HTTP_200_OK)
def forcelogout():
     ...


@get("/account",
      status_code=status.HTTP_200_OK)
def useraccount():
     ...

```

Here the issue is when I try to call the `/account` url then it return the `Not Found` exception.

Thank you.

**Comment by tarsil** [comment]
@harshalizode in the docs, it's explicitly said that if you want to do the include for all in one, in theory you should to a nested include, in your case you have 2 includes trying to reach the "/" + the the URLs from the namespace. 

What is happening? So now you have the accounts and the employee apps (includes), both in the including without a path, which means it will default to "/".  

Since Esmerald like everything, uses regex for the routes, as per docs, it will be a first found. Since both Includes have the same path, the accounts include is ignored. 

Advice? If you want both accounts and employees to be under the "/", make those includes to be inside a main Include (nested includes) or give a different path to both includes like "/accounts" and "/employees".

**Comment by harshalizode** [comment]
@tarsil can we includes more than 1 apps under "/" with the nested include?
As per the documentation They have includes for the same app urls.
Can you provide the example for this?

**Comment by tarsil** [comment]
@harshalizode literally from this section where the warning was also mentioned:

https://esmerald.dev/routing/routes/?h=nested+includes#application-routes

**Comment by harshalizode** [comment]
Okay, Thank you.
